### ISSUE TITLE
Where can I get a Credentials.swift file ?

### ISSUE THREAD

**Issue by simontokyo** [watson-developer-cloud/text-to-speech-swift#1]
Where can I get a Credentials.swift file ? I couldn't setup this project.

**Comment by schen22** [comment]
Hi, I just pushed a sample Credentials.swift skeleton file for you to use. Replace the username and password with the credentials you receive through your Watson Text to Speech service on your Bluemix account. You can find directions on how to set up the service in the [README](https://github.com/IBM-MIL/ios-sdk-watson-speaks/blob/master/README.md). Let me know if you have any other questions!

**Comment by simontokyo** [comment]
I'm grateful for your kindness. Everything is going fine. :-)

![img_0755](https://cloud.githubusercontent.com/assets/6939183/18311491/9bff29f8-753f-11e6-8ed1-e2e9d0084608.jpg)
